services:
  mcp_server:
    build: .
    container_name: exely_mcp_server
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file: .env.prod
    ports:
      - "8000:8000"
    volumes:
      - ./mcp_log.txt:/app/mcp_log.txt
    restart: always
